language:
    cpp

before_install:
    sudo apt-get -y update;

install:
    sudo apt-get -y install mono-complete;

before_script:
    cd scripts;

script:
    sh build.sh;

after_script:
    cd ../;
