#!/bin/sh
echo "{" > $HOME/.djinn.aws
echo "    \"AccountNumber\":\"xxxx-xxxx-xxxx\"," >> $HOME/.djinn.aws
echo "    \"AccessKeyId\":\"xxxxxxxxxxxxxxxx\"," >> $HOME/.djinn.aws
echo "    \"SecretKey\":\"xxxxxxxxxxxxxxxx\"," >> $HOME/.djinn.aws
echo "    \"PrivateKeyPath\":\"$HOME/.ssh/xxx.pem\"," >> $HOME/.djinn.aws
echo "    \"PrivateKeyName\":\"xxx\"," >> $HOME/.djinn.aws
echo "}" >> $HOME/.djinn.aws