#!/bin/sh
cd ../source/Sungiant.Djinn/
xbuild Sungiant.Djinn.csproj /p:Configuration=Debug /verbosity:quiet /clp:Summary /nologo

rm -r -f /usr/local/bin/djinn_app
mkdir /usr/local/bin/djinn_app

cp djinn /usr/local/bin/djinn
chmod +x /usr/local/bin/djinn

cp bin/Debug/Sungiant.Djinn.exe /usr/local/bin/djinn_app/Sungiant.Djinn.exe
cp bin/Debug/*.dll /usr/local/bin/djinn_app/

